export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_REQUEST_SUCCESS = "SIGNUP_REQUEST_SUCCESS";
export const SIGNUP_REQUEST_FAIL = "SIGNUP_REQUEST_FAIL";

export const ADD_HOTELS = "ADD_HOTELS";
export const ADD_HOTELS_SUCCESS = "ADD_HOTELS-SUCCESS";
export const ADD_HOTELS_FAIL = "ADD_HOTELS_FAIL";
export const PREVIOUS_HOTEL_DATA = "PREVIOUS_HOTEL_DATA";
export const ADD_HOTELS_DATA = "ADD_HOTELS_DATA";
export const SAVE_HOTEL_DETAILS = "SAVE_HOTEL_DETAILS";
export const UPDATE_HOTEL_DETAILS = "UPDATE_HOTEL_DETAILS";
export const DELETE_HOTEL = "DELETE_HOTEL";
export const SEARCH_HOTELS = "SEARCH_HOTELS";
export const SORT_By = "SORT_By";
export const  ROOM_DETAILS="ROOM_DETAILS";
export const SEARCH_CITY="SEARCH_CITY";
export const BOOKHOTEL="BOOKHOTEL";
export const HOTEL_BOOKING_DETAILS="HOTEL_BOOKING_DETAILS";
export const SAVE_INVOICE_DATA= "SAVE_INVOICE_DATA";
export const BOOKED_HOTELS_LIST="BOOKED_HOTELS_LIST";



export const REQUEST_STARTED = "REQUEST_STARTED";
export const REQUEST_COMPLETED = "REQUEST_COMPLETED";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_FAIL = "LOGIN_REQUEST_FAIL";

export const RESET_REQUEST_SUCCESS = "RESET_REQUEST_SUCCESS";
export const RESET_REQUEST_FAIL = "RESET_REQUEST_FAIL";

export const PASSWORD_UPDATE = "PASSWORD_UPDATE";
export const PASSWORD_UPDATE_FAIL = "PASSWORD_UPDATE_FAIL";

export const BUS_REQUEST_SUCCESS = "BUS_REQUEST_SUCCESS";
export const BUS_REQUEST_FAIL = "BUS_REQUEST_FAIL";
export const BUS_BY_ID_REQUEST_SUCCESS = "BUS_BY_ID_REQUEST_SUCCESS";
export const BUS_UPDATE_REQUEST_SUCCESS = "BUS_UPDATE_REQUEST_SUCCESS";
export const USER_SEARCH_REQUEST_SUCCESS = "BUS_UPDATE_REQUEST_SUCCESS";

export const TRAIN_REQUEST_SUCCESS = "TRAIN_REQUEST_SUCCESS";
export const TRAIN_UPDATE_REQUEST_SUCCESS = "TRAIN_UPDATE_REQUEST_SUCCESS";
export const TRAIN_REQUEST_FAIL = "TRAIN_REQUEST_FAIL";
export const TRAIN_BY_ID_REQUEST_SUCCESS = "TRAIN_BY_ID_REQUEST_SUCCESS";
export const USER_TRAIN_SEARCH_SUCCESS = "USER_TRAIN_SEARCH_SUCCESS";

export const TRAIN_TICKET_REQUEST_SUCCESS = "TRAIN_TICKET_REQUEST_SUCCESS";

export const BUS_SEATS_BOOK_SUCCESS = "BUS_SEATS_BOOK_SUCCESS";
export const BOOK_SEAT_SUCCESS = "BOOK_SEAT_SUCCESS";
export const REQUEST_BOOKED_SEATS = "REQUEST_BOOKED_SEATS";
export const REQUEST_INVOICE_BUS_DATA = "REQUEST_INVOICE_BUS_DATA";
